# Default values for rust-server-helm
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: rustdesk/rustdesk-server
  pullPolicy: IfNotPresent
  tag: "1.1.6"

url: rust.domain.local

replicaCount: 1

hbbs:
  ressources:
    limits:
      cpu: 1
      memory: 1024Mi

service:
  type: LoadBalancer

data:
  storage: 1Gi
  accessMode: ReadWriteMany
## Some providers only allow ReadWriteOnce  
#  accessMode: ReadWriteOnce
  storageClassName: standard

hbbr:
  ressources:
    limits:
      cpu: 1
      memory: 1024Mi
