apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdesk-data
spec:
  accessModes:
    - {{ .Values.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.data.storage }}
  storageClassName: {{ .Values.data.storageClassName }}
